### ISSUE TITLE
The Dark Portal event meta-issue

### ISSUE THREAD

**Issue by netherspite** [netherspite/cc-buglist#2666]
- [x] Defenders are coming back to the spawning portals and get stuck there once evaded, #2448 (high priority)
- [ ] Peon Overseer doesn't turn randomly when yelling at peons
- [ ] Horde Grunts/Shamans and Alliance Soldiers/Paladins should spawn randomly instead of being always the same
- [ ] Demon packs should have a "row" formation when coming the Path of Glory
- [ ] Demon packs should spread and take the same "row" formation instead of a group formation upon reaching the destination

**Comment by netherspite** [comment]
Peon Overseer should turn randomly one of those directions when yelling at Peons. Probably the direction depends on the phrase but it's not a big deal so could make him least turning at all.
![wowscrnshot_071318_190004](https://user-images.githubusercontent.com/5777848/42691003-94583f38-86d0-11e8-88f4-20883c50e703.jpg)
![wowscrnshot_071318_190116](https://user-images.githubusercontent.com/5777848/42691005-948a8de4-86d0-11e8-8a73-1928d475adde.jpg)
![wowscrnshot_071318_190735](https://user-images.githubusercontent.com/5777848/42691006-94bc0af4-86d0-11e8-821d-05972b64b731.jpg)

**Comment by netherspite** [comment]
Defenders formation:

![wowscrnshot_071318_183554](https://user-images.githubusercontent.com/5777848/42691059-caeab378-86d0-11e8-9700-bfcb57fd03a7.jpg)
![wowscrnshot_071318_184600](https://user-images.githubusercontent.com/5777848/42691068-d345aaa0-86d0-11e8-872d-09d5b033c0d9.jpg)

**Comment by netherspite** [comment]
Demons movement up to reaching the destination formation.

![wowscrnshot_071318_183422](https://user-images.githubusercontent.com/5777848/42691100-ece37168-86d0-11e8-9421-117d25b658cb.jpg)
![wowscrnshot_071318_183430](https://user-images.githubusercontent.com/5777848/42691101-ed153ffe-86d0-11e8-820b-a403d0ebd993.jpg)
![wowscrnshot_071318_183603](https://user-images.githubusercontent.com/5777848/42691127-00b74d7c-86d1-11e8-8fdc-fc9a2365a6fc.jpg)
![wowscrnshot_071318_183606](https://user-images.githubusercontent.com/5777848/42691129-00e9824c-86d1-11e8-9f4a-70e54dd8c8d2.jpg)
![wowscrnshot_071318_183617](https://user-images.githubusercontent.com/5777848/42691132-011c63ce-86d1-11e8-8f09-8ac88d741715.jpg)
![wowscrnshot_071318_183620](https://user-images.githubusercontent.com/5777848/42691133-014f4744-86d1-11e8-956f-3027ba0ac42a.jpg)

**Comment by netherspite** [comment]
And more packs:

![wowscrnshot_071318_183705](https://user-images.githubusercontent.com/5777848/42691174-28df9598-86d1-11e8-89f0-85ce0a5c7fda.jpg)
![wowscrnshot_071318_183708](https://user-images.githubusercontent.com/5777848/42691175-29142c72-86d1-11e8-959c-19a046a7f02d.jpg)
![wowscrnshot_071318_183712](https://user-images.githubusercontent.com/5777848/42691176-29420ce6-86d1-11e8-88ce-ba7bcbb65dcc.jpg)
![wowscrnshot_071318_183728](https://user-images.githubusercontent.com/5777848/42691177-29706618-86d1-11e8-8c30-7b6cf45ceffa.jpg)
![wowscrnshot_071318_183738](https://user-images.githubusercontent.com/5777848/42691179-29a9b6f2-86d1-11e8-8d2d-43ff5ee1509a.jpg)
![wowscrnshot_071318_183746](https://user-images.githubusercontent.com/5777848/42691180-29d6ea96-86d1-11e8-841c-a16c131836c2.jpg)

**Comment by netherspite** [comment]
Demon waves are attacking independently, probably some time after reaching their destination. 
They keep their formation when they start to attack.

![wowscrnshot_071318_183631](https://user-images.githubusercontent.com/5777848/42691212-4b8f40d4-86d1-11e8-8ecd-28b26ed42402.jpg)
![wowscrnshot_071318_183800](https://user-images.githubusercontent.com/5777848/42691213-4bc27968-86d1-11e8-9c28-805d028fd4f1.jpg)
![wowscrnshot_071318_183848](https://user-images.githubusercontent.com/5777848/42691214-4bf48a66-86d1-11e8-8807-ce02897fc5cc.jpg)
